### PR TITLE
feat: move to new openid for linkedin

### LINKED ISSUE #1: Sign in experience has been deprecated
From what I read at https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin, it seems the current sign in implementation was deprecated and no longer works for new applications. Instead, they need to be configured using openid connect: https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2.

### PR DESCRIPTION
**Pull request by natac13**
As well as follow the remix-auth-google and remix-auth-github packages closer

~~FYI I am still testing this out. I have merely just author the code and made the PR initially~~

Should:
close #1

### CODE REVIEW

**Comment by natac13** [comment]
Ok I have tested and it is working! 

This should clear up https://github.com/TheRealFlyingCoder/remix-auth-socials/issues/5

And get the LinkedIn strategy reexported by the [`remix-auth-socials`](https://github.com/TheRealFlyingCoder/remix-auth-socials) package
https://github.com/TheRealFlyingCoder/remix-auth-socials/pull/27

**Comment by Lzok** [comment]
@natac13 
Should this be a patch version or a major one? I'm asking Based on the Linkedin changes I'm not so aware of.

Regarding the code, it's ok IMO. I'll approve once I know which type of version should I release

**Comment by natac13** [comment]
Due to the change from OAuth2.0 to OpenID Connect and the scope change I think it would be best to major version bump this change with a link to the new docs https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2

Let me know if you want me to make the change in the README file for the above link.

**Comment by Lzok** [comment]
Released! https://github.com/Lzok/remix-auth-linkedin/releases/tag/v2.0.0
https://www.npmjs.com/package/remix-auth-linkedin

Could you also confirm it's working?

**Comment by natac13** [comment]
Yep I can try it out this weekend! 👍🚀

**Comment by se7entyse7en** [comment]
It is not working, check [this](https://github.com/Lzok/remix-auth-linkedin/issues/3).

**Pull request merged**
